services:
    nginx:
      container_name: nginx
      image: nginx
      build:
        context: requirements/nginx
      ports:
        - "80:80"

    wordpress:
      container_name: wordpress
      image: wordpress
      build:
        context: requirements/wordpress