services:
    mariadb:
      container_name: mariadb
      image: mariadb
      build:
        context: requirements/mariadb
      env_file:
        - .env
      volumes:
        - database:/var/lib/mysql
      networks:
        - inception
      restart: always

    nginx:
      container_name: nginx
      image: nginx
      build:
        context: requirements/nginx
      ports:
        - "443:443"
      volumes:
        - wp_data:/var/www/html
      networks:
        - inception

    wordpress:
      container_name: wordpress
      image: wordpress
      build:
        context: requirements/wordpress
      env_file:
        - .env
      expose:
        - "9000"
      volumes:
        - wp_data:/var/www/html
      networks:
        - inception
      restart: always
      
networks:
  inception:
    driver: bridge

volumes:
  wp_data:
    driver: local
    driver_opts:
      type: bind # if None, it will ignore the next options
      device: /home/azerfaou/data/wp_data
      o: bind

  database:
    driver: local
    driver_opts:
      type: bind # if None, it will ignore the next options
      device: /home/azerfaou/data/database
      o: bind