services:
    nginx:
      container_name: nginx
      image: nginx
      build:
        context: requirements/nginx
      ports:
        - "80:80"
      volumes:
        - wp_data:/var/www/html
      networks:
        - net

    wordpress:
      container_name: wordpress
      image: wordpress
      build:
        context: requirements/wordpress
      volumes:
        - wp_data:/var/www/html
      networks:
        - net
    
    mariadb:
      container_name: mariadb
      image: mariadb
      build:
        context: requirements/mariadb
      networks:
        - net
      volumes:
        - database:/var/lib/mysql
    
networks:
  net:
    driver: bridge

volumes:
  wp_data:
    driver: local
    driver_opts:
      type: bind # if None, it will ignore the next options
      device: /home/abdallah/data/wp_data
      o: bind

  database:
    driver: local
    driver_opts:
      type: bind # if None, it will ignore the next options
      device: /home/abdallah/data/database
      o: bind